vmware-tanzu/apps-cli-plugin

SECURITY.md
Adding SECURITY.md
Closes #42 
Signed-off-by: Rashed Kamal <krashed@vmware.com>
=> chore: Added Security.md

.github/workflows/ci.yaml, README.md
- Remove unused code-cov from CI and Readme badge (Closes #45) 
- Update CI badge in Readme
Signed-off-by: Rashed Kamal <krashed@vmware.com>
=> Remove code-cov, Update Readme CI badge

pkg/commands/workload_create.go
Signed-off-by: Rashed Kamal <krashed@vmware.com>
Pull request
This PR fixes the incorrect error message displayed during `tanzu apps workload create ...` scenarios. 
Fixes #49 
- Passes all unit test
- Functional tests ran locally
_When cartographer CRD not installed in the target cluster_
```
tanzu apps workload apply -f ./pkg/commands/testdata/workload.yaml
Error: no matches for kind "Workload" in version "carto.run/v1alpha1"
Error: exit status 1
```
_When workload already exists_
```
tanzu apps workload create -f ./pkg/commands/testdata/workload.yaml
Error: workload "default/spring-petclinic" already exists
Error: exit status 1
```
_When workload does not exist_
```
tanzu apps workload create -f ./pkg/commands/testdata/workload.yaml
Create workload:
1 + |---
2 + |apiVersion: …
```
=> Fixed incorrect error message for workload create

docs/usage.md, docs/working-with-workloads.md
Signed-off by: Wendy Arango warango@vmware.com
Pull request
Updating example in docs to point to a working repo
=> Updating docs to add a working example

pkg/apis/cartographer/v1alpha1/workload_helpers.go, pkg/apis/cartographer/v1alpha1/workload_test.go, pkg/apis/services/v1alpha1/resouceclaimworkloadconfig.go, pkg/apis/services/v1alpha1/resourceclaimworkloadconfig_test.go, pkg/commands/workload.go, pkg/commands/workload_test.go
Fix the bug when namespace is deleted from service reference and it was ignored in annotations. With this fix, annotations will be updated correctly.
Fixes #17 
Use the test cases in github issue
=> Removing namespace from service reference is not ignored

.github/workflows/ci.yaml
Pull request
Updating k8s matrix for CI test
Fixes #
=> Updating k8s matrix for CI

docs/command-reference/tanzu_apps_workload_apply.md, docs/command-reference/tanzu_apps_workload_create.md, docs/command-reference/tanzu_apps_workload_update.md, pkg/commands/workload.go
Pull request
Add .war as an accepted type of file in help text for `--local-path` flag 
Fixes #152 
=> Adding .war to list of accepted types of files for local path flag

pkg/commands/clustersupplychain_list.go, pkg/commands/clustersupplychain_list_test.go
Pull request
Indicate the usage of csc get in csc list to obtain details of each csc present in cluster.
Fixes #158 
=> Improve message in csc list command

.github/workflows/ci.yaml, Makefile, hack/patch-k8s-pkg-credentialprovider.patch, vendor/github.com/vdemeester/k8s-pkg-credentialprovider/provider.go
=> Add patch to k8s creds library

pkg/dies/cartographer/v1alpha1/zz_generated.die.go, pkg/dies/knative/serving/v1/zz_generated.die.go
Update dies generation for carto and knative objects
=> Update dies for objects

CONTRIBUTING.md, DEVELOPMENT.md
=> Update contribution doc

DEVELOPMENT.md
Pull request
PR will add additional instructions for installing tanzu-apps-cli in machines with arm64 processor and close issue DDF-574
Fixes # DDF-574
Tested the command in my machine Mac with M1 chip (arm64 arch) .
=> docs: Update Development.md for adding instruction to install on arm64

docs/README.md, docs/command-reference/commands-details/csc-get.md, docs/command-reference/commands-details/workload_create_update_apply.md, docs/command-reference/commands-details/workload_delete.md, docs/command-reference/commands-details/workload_get.md, docs/command-reference/commands-details/workload_list.md, docs/command-reference/commands-details/workload_tail.md, docs/debug-workload.md, docs/install-apps-cli.md, docs/usage.md, docs/working-with-workloads.md
Pull request
Update docs and add some new to explain flags usage and give examples
Needs feedback and polishing
Co-authored-by: Diego LAA <odinnordico@users.noreply.github.com>
=> Update docs to explain new features and flags usage.

pkg/apis/cartographer/v1alpha1/workload.go, pkg/commands/workload_get.go, pkg/commands/workload_get_test.go, pkg/dies/cartographer/v1alpha1/workload.go, pkg/printer/workload_status_printer.go, pkg/printer/workload_status_printer_test.go
=> feat: Adding `healthy` column to workload get command output

.github/workflows/ci.yaml, Makefile, testing/e2e/helpers/files.go, testing/e2e/suite/comand_line_integration.go, testing/e2e/suite/command_line.go, testing/e2e/suite/command_line_integration.go, testing/e2e/suite/k8s_client.go, testing/e2e/test_cases/cluster_supply_chain_get_test.go, testing/e2e/test_cases/cluster_supply_chain_list_test.go, testing/e2e/test_cases/testdata/console-out/get-csc/test-get-ci-test-csc.txt, testing/e2e/test_cases/testdata/console-out/list-csc/test-list-csc.txt, testing/e2e/test_cases/testdata/prereq/cluster-supply-chain.yaml, testing/e2e/test_cases/workload_create_test.go, testing/e2e/test_cases/workload_e2e_test.go
Adds an integration test suite with some examples of how to use it
Fixes #159 
Local run of the integration test
=> test: added integration test suite

pkg/commands/workload_test.go
Pull request
Fix unit tests which is broken at `main`
=> fix unit tests

pkg/apis/cartographer/v1alpha1/workload_serviceclaim_printer.go, pkg/apis/cartographer/v1alpha1/workload_serviceclaim_printer_test.go, pkg/cli-runtime/printer/table/interface.go, pkg/cli-runtime/printer/table/tableprinter.go, pkg/cli-runtime/printer/table/tabwriter.go, pkg/cli-runtime/printer/tabwriter/tabwriter.go, pkg/commands/clustersupplychain_get_test.go, pkg/commands/workload_get.go, pkg/commands/workload_get_test.go, pkg/printer/cluster_supply_chain_printer.go, pkg/printer/cluster_supply_chain_printer_test.go, pkg/printer/constants.go, pkg/printer/knative_service_printer.go, pkg/printer/knative_service_printer_test.go, pkg/printer/pod_printer.go, pkg/printer/pod_printer_test.go, pkg/printer/workload_overview_printer.go, pkg/printer/workload_overview_printer_test.go, pkg/printer/workload_source_printer.go, pkg/printer/workload_source_printer_test.go, pkg/printer/workload_status_printer.go, pkg/printer/workload_status_printer_test.go, testing/e2e/test_cases/testdata/console-out/get-csc/test-get-ci-test-csc.txt
Pull request
Indent get command ouput so each section is visually distinguishable
Fixes #228 
- Unit testing
- `workload get` and `csc get` in local cluster
=> Indent workload get and csc get output

pkg/commands/workload_get_test.go, pkg/printer/workload_status_printer.go, pkg/printer/workload_status_printer_test.go
Pull request
PR will add Supply chain output details to workload get command response.
Fixes #248
Added additional unit testing for supply chain details as well as workload get command.
installed the changes and tested workload get in local cluster
Signed-off-by: Shaheer Kootteeri [kshaheer@vmware.com](mailto:kshaheer@vmware.com)
=> Adds supply chain output details to workload get response

pkg/printer/workload_status_printer.go
Pull request
Bug fix for the Issue #248 to fix the appearance of supply chain output displaying in faint
Fixes #248
Installed in my local cluster and validated. 
Unit tested 
Signed-off-by: Shaheer Kootteeri [kshaheer@vmware.com](mailto:kshaheer@vmware.com)
=> change appearance of supply chain output

pkg/printer/workload_status_printer.go, pkg/printer/workload_status_printer_test.go
Pull request
bug fix issue 253 to hide health condition when no resource healthy message 
Fixes #253
unit testing added for empty message as well as with valid messages
tested in local cluster
=> hide healthcondition when no message

.github/workflows/rebase.yaml
=> Fix CI rebase yaml

docs/commands-details/workload_get.md, pkg/apis/cartographer/v1alpha1/deliverable.go, pkg/apis/cartographer/v1alpha1/workload.go, pkg/commands/workload_get.go, pkg/commands/workload_get_test.go, pkg/printer/helpers.go, pkg/printer/workload_deliverable_printer.go, pkg/printer/workload_status_printer.go, pkg/printer/workload_status_printer_test.go
Pull request
Removes `Deliverable` row from supply chain resources in `get` output
Fixes #257 
Local install of apps plugin against a Tap1.2 cluster getting the same `Workload`
=> feat: removed deliverable of supplychain table

pkg/commands/workload.go, pkg/flags/env_var.go
=> Refactor env var 

docs/commands-details/workload_create_update_apply.md
Adds `--registry-ca-cert`, `--registry-password`, `--registry-token`, `--registry-username` documentation in commands details
N/A
N/A
N/A
=> docs: Added registry flags to command details

pkg/commands/workload.go, pkg/commands/workload_test.go, pkg/dies/cartographer/v1alpha1/zz_generated.die.go, pkg/dies/knative/serving/v1/zz_generated.die.go, pkg/logger/uilogger.go, pkg/printer/pod_printer_test.go, pkg/source/imgpkg.go
Pull request
Refactor function names. Looks like we missed this in review. This is refactor PR.
=> Update function names for imgpkg logger 

.github/workflows/ci.yaml, DEVELOPMENT.md, go.mod, hack/go.mod
Pull request
Upgrade to go1.19. Use the same version in CI as well
Fixes #300
=> Upgrade to go1.19

.github/workflows/ci.yaml, Makefile, pkg/cli-runtime/options.go, pkg/cli-runtime/printer/table/tablegenerator.go, pkg/cli-runtime/printer/tabwriter/tabwriter.go, testing/e2e/cluster_supply_chain_test.go, testing/e2e/testdata/console-out/get-csc/test-get-ci-test-csc.txt, testing/e2e/testdata/console-out/list-csc/test-list-csc.txt, testing/e2e/workload_test.go, testing/suite/integration.go
Changed cluster supply chain e2e so it runs for all clusters
Add skip to e2e tests if not required Env Vars are set
Added local private registry in ci for ca cert tests
Fixes #303 
local test with `make integration-test` and ci test in fork: https://github.com/odinnordico/apps-cli-plugin/actions/runs/2965680066
=> test: Fixed e2e test to work in local and ci

pkg/commands/workload.go, pkg/commands/workload_test.go, pkg/logger/fake/fake_progress_logger.go, pkg/logger/progress_logger.go, pkg/logger/progress_logger_test.go, pkg/logger/uilogger.go, pkg/logger/uilogger_test.go, pkg/source/imgpkg.go, pkg/source/registry.go, testing/e2e/workload_test.go
Pull request
PR adds progress bar with image size to the `--local-path `workflow for workload create and apply commands.
Fixes #225 
Installed in local and validated against the local cluster
=> Adds progress image to the local source create

pkg/source/archive_test.go
Pull request
PR fixes test cases that are failing in windows for archive file due the line break differences in different oS.
Fixes #334 
Validated executing unit test cases in mac as well as windows OS, also installing them.
=> fixes test cases that are failing in windows for archive file

pkg/cli-runtime/wait/wait_test.go
Pull request
fixes test cases for wait file which was erroring when testing in windows OS
Fixes #332 
Validated unit test cases in mac as well as windows.
=> fixes test cases for wait file

pkg/commands/workload_test.go, pkg/source/imgpkg.go
Pull request
PR fixes the paths in the workload test file to use filepath library to make OS agnostic 
Fixes #
Tested unit test cases in both Mac as well as windows machine
=> fixes paths in workload test file to use filepath library

docs/commands-details/workload_get.md, pkg/commands/workload_get_test.go, pkg/printer/workload_overview_printer.go, pkg/printer/workload_overview_printer_test.go
Pull request
Add namespace to workload get output in `Overview` section
Fixes #321 
- Updated unit testing
=> Add namespace to workload get overview section

cmd/plugin/apps/main.go, docs/command-reference/tanzu_apps.md, docs/command-reference/tanzu_apps_cluster-supply-chain.md, docs/command-reference/tanzu_apps_cluster-supply-chain_get.md, docs/command-reference/tanzu_apps_cluster-supply-chain_list.md, docs/command-reference/tanzu_apps_workload.md, docs/command-reference/tanzu_apps_workload_apply.md, docs/command-reference/tanzu_apps_workload_create.md, docs/command-reference/tanzu_apps_workload_delete.md, docs/command-reference/tanzu_apps_workload_get.md, docs/command-reference/tanzu_apps_workload_list.md, docs/command-reference/tanzu_apps_workload_tail.md, docs/command-reference/tanzu_apps_workload_update.md, go.mod, pkg/cli-runtime/config.go, pkg/cli-runtime/config_test.go, pkg/cli-runtime/emoji.go, pkg/commands/workload_get.go, pkg/commands/workload_get_test.go, testing/e2e/cluster_supply_chain_test.go, testing/e2e/workload_test.go, testing/suite/command_line.go, testing/suite/integration.go
Pull request
Do not print emojis when using `--no-color` flag with `workload get`
Fixes #301 
- Added unit testing
- Added e2e tests
Refer to #314 for more info
=> Do not print emojis when no color is set

pkg/commands/workload_get_test.go
Pull request
Fix unit tests that overlapped between PRs
Fix tests
=> test: Correct latest test to match other features in main branch

docs/commands-details/workload_create_update_apply.md, docs/commands-details/workload_get.md, docs/debug-workload.md, pkg/commands/workload.go, pkg/commands/workload_apply_test.go, pkg/commands/workload_create_test.go, pkg/commands/workload_get.go, pkg/commands/workload_get_test.go, pkg/commands/workload_update_test.go
Pull request
Update `tail` help message in workload create/apply/get so it will tell users to use `timestamp` and `since` flags 
Fixes #369 
- Updated unit testing
=> Update tail help message

.github/workflows/ci.yaml, Makefile
Pull request
PR adds unit tests on windows runner in CI.
Fixes #160 
CI commands have been ran successfully in windows as well as ubuntu runner.
=> Adds unit tests in CI on windows runner

.github/workflows/ci.yaml
Pull request
Pull request adds mac os runner to the CI for unit test cases.
Fixes #329
Validated the e2e CI in github actions successfully. Also validated the scripts on local mac machine terminal.
=> Adds mac-os runner for CI

pkg/commands/workload.go, pkg/commands/workload_apply_test.go, pkg/commands/workload_test.go, testing/e2e/workload_test.go
Pull request
Add the capability to use remote file (URL) to create/apply a workload
Fixes #372 
- Updated unit test
- Updated e2e test
=> feat: Allow users to pass url for --file flag

.github/workflows/ci.yaml
Pull request
Update windows runner in CI  to use build dev version.
=>  use dev build version for windows runner

.github/workflows/ci.yaml, Makefile
Pull request
Updates the CI as well as MAKE file to remove repeating tasks.
Fixes #
Validated all the make commands in local cluster as well as ran CI successfully.
=> Updates Make file as well as CI for unit test

docs/command-reference/tanzu_apps_workload_create.md, pkg/commands/workload_create.go
Pull request
Update `tanzu apps workload create` example so it shows the correct command usage
Fixes #417 
=> fix: Update workload create example with correct usage

cmd/plugin/apps/main.go, docs/command-reference/tanzu_apps.md, docs/command-reference/tanzu_apps_cluster-supply-chain.md, docs/command-reference/tanzu_apps_cluster-supply-chain_get.md, docs/command-reference/tanzu_apps_cluster-supply-chain_list.md, docs/command-reference/tanzu_apps_workload.md, docs/command-reference/tanzu_apps_workload_apply.md, docs/command-reference/tanzu_apps_workload_create.md, docs/command-reference/tanzu_apps_workload_delete.md, docs/command-reference/tanzu_apps_workload_get.md, docs/command-reference/tanzu_apps_workload_list.md, docs/command-reference/tanzu_apps_workload_tail.md, docs/command-reference/tanzu_apps_workload_update.md, pkg/commands/workload.go, pkg/logger/uilogger.go, pkg/source/imgpkg.go, pkg/source/registry.go, testing/e2e/workload_test.go
Pull request
Hide progress bar when `--no-color` is set
Fixes #440 
=> feat: Remove progressbar when --no-color flag is set

Makefile
Pull request
tests are failing on local machines because of a timeout, this may be related to the amount of tests or to the machines resources. This PR is meant to give it more time to process before they fail.
N/A
=> Give more time to tests in make test before they fail

.github/workflows/ci.yaml
Pull request
PR updates the matrix to add k8s 1.26 version
Fixes #
validated the CI after updating the k8s version
=> chore: updates matrix with  k8s version 1.26

docs/command-reference/tanzu_apps_workload_get.md, docs/commands-details/workload_get.md, docs/how-to-guides.md, pkg/commands/workload_get.go
Pull request
Add -e as shorthand for --export flag
Fixes #388
=> Add -e as shorthand for --export flag

codecov.yml
Pull request
PR updates the codecov.yaml file to add additional files or folders to the ignore section to not to report on these.
Fixes #
validated the codecov report generated for the PR
=> updates codecov ignore files

pkg/cli-runtime/wait/wait.go, pkg/commands/workload.go, pkg/commands/workload_apply.go, pkg/commands/workload_create.go
Pull request
Add some validations to caught `nil` objects in `UntilCondition` function so apps plugin does not panic if there is an error in `wait/tail` commands
Fixes #476
=> Do not panic with wait error for wait/tail commands

pkg/commands/workload.go, pkg/commands/workload_apply.go, pkg/commands/workload_create.go, pkg/commands/workload_test.go, pkg/commands/workload_update.go
Pull request
Remove unnecessary prompt when publishing local source 
Fixes #472
=> Delete prompt for PublishLocalSource

.github/workflows/ci.yaml, DEVELOPMENT.md, Makefile
Pull request
When releasing, publish OCI artifact to Github Container Registry so it's publicly accessible. 
Fixes #491 
- Created new tag in fork to test it actually publishes
- Used `tanzu builder` command (publish oci) locally to test the push
- Updated docs to explain step by step how to publish a local dev version to ghcr
=> Publish release as OCI artifact stored in ghcr

docs/commands-details/workload_create_update_apply.md, docs/commands-details/workload_get.md, docs/create-workload.md, docs/how-to-guides.md
Pull request
Docs updates
N/A
N/A
=> Update docs to add latest explain and give examples of latest changes

docs/command-reference.md
Pull request
The update subcommand was removed from apps workload plugin but there was still a reference of it in the documentation
Fixes N/A
=> chore: Removed reference to update subcommand docs

pkg/commands/lsp/lsp.go, pkg/commands/lsp/lsp_test.go
Pull request
When an error occurs calling LSP or when LSP returns a message which contains url encoded text (% followed by two hexadecimal digits), it is shown as it comes.
This PR try to use a URL Decoding strategy to show better the message from LSP, if the decoding strategy fails it shows the message as is
Fixes #540
=> fix: Use url decode in the output message from lsp

.github/workflows/ci.yaml, .wokeignore, hack/woke/its-woke-rules.yaml
Pull request
Add woke rules yaml file in project to avoid errors when trying to access it URL
N/A
=> fix: Add woke rules in project
