- pkg/commands/clustersupplychain_list.go
- pkg/commands/clustersupplychain_list_test.go
Pull request
Removing LABEL SELECTOR column in `clustersupplychain list` command
Fixes #15
- Unit testing
- Use command in local cluster to check accuracy of output
Signed-off by: Wendy Arango warango@vmware.com
> Removing LABEL SELECTOR column in clustersupplychain list command

- .github/workflows/ci.yaml
- docs/command-reference/tanzu_apps_workload_list.md
- pkg/cli-runtime/printer/resource.go
- pkg/cli-runtime/printer/resource_test.go
- pkg/commands/workload_list.go
- pkg/commands/workload_list_test.go
Add `--output` flag to workloads list command.  This flag supports both yaml and json format
Fixes #12
```
tanzu apps workload list --output json
[
{
"kind": "Workload",
"apiVersion": "carto.run/v1alpha1",
"metadata": {
"name": "petclinic",
"namespace": "default",
.....
}
]
```
> Add support for --output flag to workloads list command

- pkg/cli-runtime/client.go
Signed-off-by: Rashed Kamal <krashed@vmware.com>
Pull request
This PR fixes the UX error message when kubeconfig is missing or the current context is no longer valid.  
Fixes #53 
- Unit test
- Local test 
_Missing Kubeconfig_
```
➜  ~  tanzu apps workload list -n workspace
Error: Unable to connect: no configuration has been found. If a kubeconfig is not set, it can be provided with the --kubeconfig flag or KUBECONFIG environment variable.
Error: exit status 2
✖  exit status 2
```
_Missing Kubeconfig Verbose_
```
➜  ~  tanzu apps workload list -n workspace -v 2
Error: Unable to connect: no configuration has been found. If a kubeconfig is not set, it can be provided with the --kubeconfig flag or KUBECONFIG environment variable.
API Error name:tanzu apps  error:invalid configuration: no …
```
> Error message for missing Kubeconfig and Non-existent context

- pkg/cli-runtime/printer/resource.go
- pkg/cli-runtime/printer/resource_test.go
Pull request
Previously empty list would generate `null` as output, this is updated to print empty array for both json and yaml.
Fixes #12
> Update output for list when there are no workloads

- pkg/commands/workload_get.go
- pkg/commands/workload_get_test.go
- pkg/printer/workload_source_printer.go
- pkg/printer/workload_source_printer_test.go
Pull request
Add source info when retrieving a workload with apps workload get command. In this PR, sub-path is also added to displayed output
Fixes #10 
Fixes #21 
Signed-off by: Wendy Arango warango@vmware.com
> Adding source info from workload spec to workload get command

- docs/command-reference/tanzu_apps_workload_get.md
- docs/command-reference/tanzu_apps_workload_list.md
- pkg/cli-runtime/printer/resource.go
- pkg/commands/workload_get.go
- pkg/commands/workload_get_test.go
- pkg/commands/workload_list.go
- pkg/commands/workload_list_test.go
- pkg/printer/aliases.go
Pull request
Add support for yml extension when user wants to output a resource through workload get or workload list commands.
Output will be same if user wants to show it with yaml format.
Usage example:
`tanzu apps workload get my-workload -oyml`
`tanzu apps workload list -oyml`
Fixes #72 
- Unit testing in source code
- Used commands in local cluster
Signed-off by: Wendy Arango warango@vmware.com
> Adding yml to accepted output formats

- pkg/apis/cartographer/v1alpha1/groupversion_info.go
- pkg/apis/cartographer/v1alpha1/groupversion_info_test.go
- pkg/commands/workload_get.go
- pkg/commands/workload_get_test.go
- pkg/commands/workload_list.go
- pkg/commands/workload_list_test.go
- pkg/commands/workload_update.go
- pkg/commands/workload_update_test.go
New behaviour:
```
tanzu apps workload update pc -n ns2 
Error: namespace "ns2" not found, it may not exist or user does not have permissions to read it.
Error: exit status 1
✖  exit status 1 
```
```
tanzu apps workload list -n ns2                 
Error: namespace "ns2" not found, it may not exist or user does not have permissions to read it.
Error: exit status 1
✖  exit status 1 
```
```
tanzu apps workload get pc -n ns2               
Error: namespace "ns2" not found, it may not exist or user does not have permissions to read it.
Error: exit status 1
✖  exit status 1 
```
Fixes #18 
For commands `create/apply` sub-command, when namespace does not exist the above error is not thrown. This is because of `NamespaceAutoProvision` on …
> Update workload commands list/get/update when bogus namespace is passed

- pkg/commands/clustersupplychain.go
- pkg/commands/workload.go
Pull request
Adds alias support to short-names of carto workload and cluster supply chain
Fixes #96 
Local test of the command
> feat: support shortnames for carto's workload and cluster supplychain

- pkg/apis/cartographer/v1alpha1/workload_helpers.go
- pkg/commands/testdata/workload-subPath.yaml
- pkg/commands/workload_apply.go
- pkg/commands/workload_apply_test.go
- pkg/commands/workload_update.go
Pull request
subpath field is not ignored when submitting workload from file(both while creating & updating)
Fixes #88 
- create workload with subPath
- export the workload into a file
- apply the workload again, subPath should not be deleted
> subpath field is not removed when submitting workload from file

- pkg/apis/cartographer/v1alpha1/workload_helpers.go
- pkg/apis/cartographer/v1alpha1/workload_test.go
- pkg/commands/workload.go
- pkg/commands/workload_apply_test.go
- pkg/commands/workload_create_test.go
- pkg/commands/workload_test.go
- pkg/commands/workload_update_test.go
Add a info level msg for workload create/apply/update when no source is present
Fixes #154 
- if workload is created with no source but subPath is provided : fails
> Add a msg for workload sub commands when no source is present

- pkg/commands/workload.go
- pkg/commands/workload_apply.go
- pkg/commands/workload_apply_test.go
- pkg/commands/workload_create.go
- pkg/commands/workload_create_test.go
- pkg/commands/workload_get.go
- pkg/commands/workload_get_test.go
- pkg/commands/workload_update.go
- pkg/commands/workload_update_test.go
Pull request
Add hint message for commands that can be used for troubleshooting or just check status of a workload.
- For create/update/apply: add hint so user can check logs and status through tail and get commands
- For get: add hint so user can check logs through tail command
Fixes #150 
- Unit testing
- Test in local cluster
> Add hint message in workload create/update/apply/get

- .github/workflows/ci.yaml
Update CI file to exclude jar and zip files in Grype scan. This should remove the warning msgs from CI logs.
> Exclude jar and zip files in Grype scan

- pkg/commands/workload_apply.go
- pkg/commands/workload_apply_test.go
- pkg/commands/workload_create.go
- pkg/commands/workload_create_test.go
- pkg/commands/workload_update.go
- pkg/commands/workload_update_test.go
Pull request
remove redundant message pointing to workload get when there is an error after wait in workload create/update/apply
Fixes #183 
- Updated unit testing
- Checked commands behaviour in local cluster
> Delete info message pointing to workload get after wait error

- cmd/plugin/apps/main.go
Pull request
Hide `azure-container-registry-config`, that comes from imgpkg library and it's not used in apps plugin
Fixes #171 
- Built in local cluster to check flag is not printed in help message.
Co-authored-by: Shash Reddy <shashwathi@users.noreply.github.com>
> bug: Delete unused flag coming from imgpkg

- pkg/commands/workload_list.go
- pkg/commands/workload_list_test.go
Pull request
Modified the workload LIST command output to list the TYPE of the workloads
Fixes # 
Modified the workload_list_test.go file to include the test scenarios with TYPE int he results.
Added TYPE label for yaml, json as well with and without values in the test cases.
Fixed the issue 223 for workload list commands
> Adding type to the workload LIST output

- pkg/commands/workload_get.go
- pkg/commands/workload_get_test.go
- pkg/printer/workload_overview_printer.go
- pkg/printer/workload_overview_printer_test.go
Pull request
Modified the workload GET command output to list the TYPE of the workload. The type is listed under Overview section in the output.
Fixes # 223
Unit test cases updated to validate the new Overview section with the type details. Added unit test cases to validate the over print file.
Test in local cluster
Fixes the issue 223 for the get command output
> Adding overview in the output for workload get

- pkg/apis/cartographer/v1alpha1/workload.go
- pkg/commands/workload_get_test.go
- pkg/dies/cartographer/v1alpha1/workload.go
- pkg/printer/workload_status_printer.go
- pkg/printer/workload_status_printer_test.go
Pull request
Add HEALTHY column to surface the healthy status of each resource in workload get output
Fixes #215 
- Unit testing
- Test in local cluster
> Adding healthy column to workload get resources output

- pkg/cli-runtime/printer/format.go
- pkg/cli-runtime/printer/format_test.go
- pkg/printer/workload_overview_printer.go
- pkg/printer/workload_status_printer.go
Pull request
Add color to `HEALTHY` column in workload get output so it helps users to better visualize and distinguish the status of every step of their workload. 
Fixes #227 
Color code is
`true`=green/good
`false`=red/bad
`unknown`=cyan
> chore: Add color to healthy column

- pkg/commands/workload.go
- pkg/commands/workload_apply.go
- pkg/commands/workload_create.go
- pkg/commands/workload_test.go
- pkg/commands/workload_update.go
Pull request
when the local source hasnt changed, display info `No sourc code is changed`, instead of `Published source`.
Fixes #175 
case when no change in code + no change in spec
```
% tanzu apps workload apply pet-img-6 --source-image gcr.io/SOMETHING/petclinictestjar:source --local-path /Users/snagarajared/workspace/spring-petclinic/target/spring-petclinic-2.6.0-SNAPSHOT.jar  
? Publish source in "/Users/snagarajared/workspace/spring-petclinic/target/spring-petclinic-2.6.0-SNAPSHOT.jar" to "gcr.io/SOMETHINGpetclinictestjar:source"? It may be visible to others who can pull images from that repository Yes
Publishing source in "/Users/snagarajared/workspace/spring-petclinic/target/spring-petclinic-2.6.0-SNAPSHOT.jar" to "gcr.io/SOMETHING/petclinictestjar:source"...
No source code is …
```
> Display info when there is no change in local source 

- .github/workflows/rebase.yaml
Pull request
Apps plugin had 2 PRs recently merged in that broke `main` branch. Enabling `/rebase` command to rebase PR and re-run tests.
> Enable automatic rebase for PR

- pkg/printer/workload_deliverable_printer.go
- pkg/printer/workload_deliverable_printer_test.go
- pkg/printer/workload_status_printer.go
- pkg/printer/workload_status_printer_test.go
Prevent messages to be printed when the actual condition message is empty
Fixes #251
> fix: hide ready message when empty

- docs/working-with-workloads.md
- pkg/flags/env_var.go
- testing/e2e/workload_test.go
Removes TANZU_APPS_SOURCE_IMAGE environment variable from allowed to use as default
Fixes #
> fix: remove TANZU_APPS_SOURCE_IMAGE from allowed

- pkg/apis/cartographer/v1alpha1/workload_helpers.go
- pkg/apis/cartographer/v1alpha1/workload_test.go
- pkg/commands/workload_apply_test.go
When maven `type` flag is passed, update the workload to recognize the flag.
Follow up for fixes #170
> Recognize maven type flag

- pkg/commands/workload.go
- pkg/commands/workload_apply.go
- pkg/commands/workload_apply_test.go
- pkg/commands/workload_create.go
- pkg/commands/workload_create_test.go
Validates if the provided namespace can be accessed by the user when validating if workload exists.
Fixes #271 
Loca installation of plugin against TAP1.2 cluster in GKE
Try to create a workload from source code in the default namespace and a non-existing namespace.
This validation applies to all the `apply`/`create` subcommands, if the namespace does not exist or is not accessible for the user it will throw an error
> fix: validate namespace when validating workload

- pkg/commands/workload_get.go
- pkg/commands/workload_get_test.go
- pkg/printer/workload_overview_printer.go
- pkg/printer/workload_overview_printer_test.go
When `get` a workload the status within the name is shown based on the workload resources but not a combination of workload resources and delivery resources the the status is being removed and the status should be calculated checking the resources.
Fixes #278 
Getting workloads with local install of the plugin from TAP1.2 cluster on GKE
N/A
> feat: Moved workload to overview and  remove status

- pkg/cli-runtime/config.go
- pkg/cli-runtime/config_test.go
- pkg/cli-runtime/emoji.go
- pkg/commands/workload_get.go
- pkg/commands/workload_get_test.go
- testing/e2e/workload_test.go
Pull request
PR adds emojis to the workload get output command
Fixes #262 
Added unit test cases with Emojis. Modified integration test to validate the emojis in the output. tested in local cluster.
> Adds Emojis to the workload get output

- pkg/cli-runtime/client_test.go
- pkg/cli-runtime/config_pkg_test.go
Pull request
PR fixes client and config package test cases to support all OS file paths. 
Fixes #330 
Reran all the unit test cases in Mac as well as windows OS, also ran make commands to install successfully.
> Fixes file path issue in client test file for windows

- pkg/commands/workload_apply_test.go
- pkg/commands/workload_create_test.go
- pkg/commands/workload_delete_test.go
- pkg/commands/workload_update_test.go
…ate apply create and delete
Pull request
PR updates wait timeout test cases for workload update, create , apply and delete in windows OS.
Fixes #337 
Validated the unit test cases in windows as well as MAC. Also validated the commands installing them on local machine.
> skipping wait timeout test cases for windows OS in workload commands

- .github/workflows/ci.yaml
Pull request
PR adds k8s versions 1.24.6 and 1.25.2 to the matrix for acceptance testing. Also updated the kind binary version to the latest that supports the k8s 1.25.2 
Fixes #
The CI ran successfully for all the matrix versions
> updates k8s version to latest

- pkg/commands/workload_apply.go
- pkg/commands/workload_apply_test.go
- pkg/commands/workload_create.go
- pkg/commands/workload_create_test.go
- pkg/commands/workload_tail.go
- pkg/commands/workload_tail_test.go
- pkg/commands/workload_update.go
- pkg/commands/workload_update_test.go
Pull request
updates the default time for workload tail from 1 second to 1 minute in workload create apply tail or update command. It reduces the number of occurrences of the init container logs being added and removed
Fixes #30 
updated unit test cases to have tail function use the default value as 1 mint and validated the cli in local cluster as well.
> fixes Tail output for init container being displayed extra

- Makefile
Pull request
If build version env var is set then use that instead of apps plugin version
Released build contains dev version
> Fix CI to use build version from env

- .github/workflows/ci.yaml
Pull request
Windows runner requires `env:` prefix to get environment variables.
> Use `env:` prefix to fetch env vars in windows

- pkg/apis/cartographer/v1alpha1/workload_helpers.go
- pkg/apis/cartographer/v1alpha1/workload_test.go
Pull request
Avoid deleteting subpath when there is an update to other source specifications, as source image or git reference. 
Fixes #431 
- Created/updated various workloads with different source specifications 
- Added unit testing 
In the GitHub issue, there was a description relating this error to Git references, but it happens to be also affecting source image specification, so whenever the image was updated, if there was a subpath, was being deleted in the process. 
This PR also addresses and corrects this behaviour.
> Do not delete subpath when there are updates to source spec

- pkg/apis/cartographer/v1alpha1/workload_helpers.go
- pkg/apis/cartographer/v1alpha1/workload_test.go
- pkg/commands/workload_apply_test.go
- testing/e2e/workload_test.go
Pull request
Because of a [FluxCD bug](https://github.com/fluxcd/source-controller/issues/315), apps plugin would not allow users to pass a git commit to take the source from when creating a workload, so there was always a need to specify either `--git-branch` or `--git-tag`. There is an [upstream fix](https://github.com/fluxcd/source-controller/pull/462) in the newer versions of FluxCD and TAP has been updated to use the latest (`v0.17.1+`), so apps plugin can also be updated to allow users to create their workload using only `--git-commit`
Fixes #179 
Fixes #28 
- Created workloads in cluster using the three flags (`--git-commit`, `--git-tag`, `--git-branch`), each separated, and combination of these. 
- Added/updated unit testing
- Updated e2e test
Signed-off-by: Wendy Arango …
> fix: Allow user to pass only git commit for git ref

- pkg/apis/cartographer/v1alpha1/workload_helpers.go
- pkg/apis/cartographer/v1alpha1/workload_test.go
- pkg/commands/workload.go
- pkg/commands/workload_apply_test.go
- pkg/commands/workload_test.go
Pull request
Allow to remove git fields from workload by passing them as empty strings through flags.
Fixes #424 
- Modified different workloads in local cluster
- Added unit tests
> Allow users to unset git flags by passing them as empty string

- docs/command-reference/tanzu_apps_workload_apply.md
- docs/command-reference/tanzu_apps_workload_create.md
- docs/command-reference/tanzu_apps_workload_update.md
- pkg/cli-runtime/config.go
- pkg/cli-runtime/config_test.go
- pkg/commands/workload.go
- pkg/commands/workload_apply.go
- pkg/commands/workload_apply_test.go
- pkg/commands/workload_create.go
- pkg/commands/workload_create_test.go
- pkg/commands/workload_test.go
- pkg/commands/workload_update.go
Pull request
Add `--output` flag to create/apply to retrieve workload once it's ready (mostly for scripting purposes)
Fixes #392 
> Add --output flag to create/apply

- pkg/apis/cartographer/v1alpha1/workload.go
- pkg/commands/workload_get_test.go
- pkg/printer/workload_source_printer.go
- pkg/printer/workload_source_printer_test.go
Pull request
Add git revision to `workload get` so users can know which revision their workload checked out to.
Fixes #428 
- Added unit test
- Created different workloads with `--git-commit`, `--git-branch` and/or `--git-tag` to check the `workload get` behaviour after retrieving the workload.
From issue description:
> 1. add a `revision` name/value pair to the `Source` section of `tanzu apps workload get` 
>     * in the event the user has passed in the specific commit sha, the `revision` shouldn't be added to the `source` section because that information will be redundant with what's already there
> 2. in the case where sub-path and branch are provided, re-order the location of the branch so the source name/value pairs are ordered by increasing level of specificity (type, url, branch, …
> feat: Add git revision in workload get

- pkg/cli-runtime/printer/resource.go
- pkg/cli-runtime/printer/resource_test.go
- pkg/commands/workload.go
- pkg/commands/workload_apply.go
- pkg/commands/workload_apply_test.go
- pkg/commands/workload_create.go
- pkg/commands/workload_create_test.go
- pkg/commands/workload_get_test.go
- pkg/commands/workload_test.go
Pull request
Remove the waiting step when using `--output` flag since this behavior does not resemble `kubectl`.
Fixes #487 
- Added unit test
- Created different workloads using `--output` flag with and without `--yes` and checked that output is the same as `kubectl get workload my-workload -oyaml`
- Added capability to `wait`, `tail` along with `--output`. `wait` will only print the info messages when user does not pass `--yes` to be consistent with the rest of the functionality.
- `tail`, per obvious reasons, will display all the steps info.
- Both of them, after their wait time is over or the workload is in a `ready` status, will return the workload as is in the cluster.
- If user does not pass `wait` or `tail`, then the command will return immediately.
> Do not wait for workload to be ready when using --output flag

- .github/workflows/ci.yaml
- DEVELOPMENT.md
- Makefile
- go.mod
- hack/go.mod
Pull request
Update go version to 1.20.x in apps-cli. Also updating the CI to run tests on go version 1.20.x.
Fixes #
Validated unit tests as well as integration tests successfully. Installed the app in my local and validated against a local cluster. 
The coverage details on integration tests were causing failures with error   ` error generating coverage report: write /dev/pts/3: file already closed`.It is probably due to changes in [os/exec](https://tip.golang.org/doc/go1.20#os/exec) package. This pull request removes the covermod from integration tests as it was neither generating a coverage report, nor we are using the report in the CI. Proposing to enhance the coverage report introducing coverage for integration as well as unit tests using the latest features in GO 1.20
> Update go version to 1.20.x

- pkg/cli-runtime/client.go
- pkg/cli-runtime/flags.go
- pkg/commands/clustersupplychain_list.go
- pkg/commands/workload.go
Pull request
Add autocompletion func for `--type` flag. 
Fixes #360 
- Modified OOTB supply chain to have different selectors besides `web`, `server`, `worker` and showed also the custom ones.
> Add autocompletion for type flag

- pkg/cli-runtime/logs/stern.go
Pull request
With Stern new version ([v1.24.0](https://github.com/stern/stern/releases/tag/v1.24.0)), a new flag was introduced to decide which is the maximum number of concurrent requests. In Apps Plugin code, it never gets to have a default number other than 0, that's why, if not specified in Stern configuration, logs would never appear since there weren't any allowed logs to show.
A number of the maximum Int16 (32767) was set as the max log requests for Stern, which means there can be up to that amount of pods logging at the same time for Apps Plugin `workload tail` or `workload create/update/apply --tail` to work.
Another change introduced in Stern was the `ALL_STATES` option for containers state filter. It was also added in Apps Plugin so all containers are shown …
> Add max log requests for stern tailer

- pkg/commands/lsp/lsp.go
- pkg/commands/lsp/lsp_test.go
Pull request
Although in TAP 1.6+, LSP will be provisioned by default on TAP iterate clusters, we can’t assume developers will always be pointing to a TAP env where LSP exists or is running/healthy.
This PR fixes the LSP health response validation to take all the 2xx HTTP codes as a healthy answer
Fixes #523
> fix: handle 2xx status as healthy lsp

- pkg/commands/workload.go
- pkg/commands/workload_apply.go
- pkg/commands/workload_apply_test.go
- pkg/commands/workload_create.go
- pkg/commands/workload_create_test.go
- pkg/commands/workload_update.go
- pkg/commands/workload_update_test.go
Pull request
When creating a workload using the local source proxy or updating a workload created using the local source proxy, the health is called before the local source start being updated.
Fixes #523 
Created a workload with using local source proxy and then editing it
changing the secrets on lsp to fail
> feat: Check LSP health when create/update a workload

- pkg/commands/workload.go
- pkg/commands/workload_apply.go
- pkg/commands/workload_apply_test.go
- pkg/commands/workload_create.go
- pkg/commands/workload_create_test.go
- pkg/commands/workload_update.go
- pkg/commands/workload_update_test.go
Pull request
When applying changes to a workload, if it was previously in a fail state, then the plugin won't wait until the new changes are applied and instead fails with the old error. This PR fixes and allows the plugin to wait until the workload actually changes its status.
Fixes #450
> fix: Do not fail when waiting to apply workload changes

- pkg/commands/localsourceproxy_health_test.go
- pkg/commands/lsp/lsp.go
- pkg/commands/lsp/lsp_test.go
- pkg/commands/workload.go
- pkg/commands/workload_apply_test.go
- pkg/commands/workload_create_test.go
…as worklaod apply and create output
Pull request
PR updates the workload apply and create output error message as well as` tanzu apps lsp health` command error output to display `Reasons` and `Messages` instead of `Error` and `Errors` respectively.
Fixes #550 
Since the code for generating error messages based on response error codes are reused between tanzu apps workload commands as well as tanzu apps lsp health command, product agreed to change  the message that are common for both commands . 
Example :- 
lsp health command output 
```
user_has_permission: true
reachable: true
upstream_authenticated: false
overall_health: false
message: |-
Local source proxy was unable to authenticate against the target registry.
Errors:
- GET …
```
> Updates the LSP Error messages in the health and workload output

- docs/command-reference/tanzu_apps_workload_apply.md
- docs/command-reference/tanzu_apps_workload_create.md
- pkg/cli-runtime/wait/wait.go
- pkg/cli-runtime/wait/wait_test.go
- pkg/commands/workload.go
- pkg/commands/workload_apply.go
- pkg/commands/workload_apply_test.go
- pkg/commands/workload_create.go
- pkg/commands/workload_create_test.go
- pkg/flags/flags.go
Pull request
This PR addresses use case when `workload apply` is used along with `--wait` and/or `--tail` command to update an existing workload - apps CLI considers transition between steps to being workload ready and exits. With this fix it waits (default `30s`) to let the intermittent step transition to ensure supply chain progress is captured accurately.
Fixes #
> feat: add delay time to prevent exit before supply chain is ready
